import Footer from '../src/components/footer'
import Nav from '../src/components/nav'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Outlet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
